# -*- coding: utf-8 -*-
"""CRLB INTERN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GCxlfBlZILxNgoWcbLnVz9TND_A8zSXh
"""

import numpy as np

def generalized_crlb(theta, log_likelihood, data, eps=1e-6):

    # ---- SCORE FUNCTION (DERIVATIVE OF LOG-LIKELIHOOD) ----
    def score(theta, x):
        return (log_likelihood(theta + eps, x) -
                log_likelihood(theta - eps, x)) / (2 * eps)

    # ---- COMPUTE SCORE FOR ALL DATA REALIZATIONS ----
    scores = np.array([score(theta, x) for x in data])

    # ---- FISHER INFORMATION (EXPECTATION OF SCORE^2) ----
    fisher_information = np.mean(scores**2)

    # ---- CRAMÉR–RAO LOWER BOUND ----
    crlb = 1 / fisher_information

    return crlb

import numpy as np
import pandas as pd
from google.colab import files
import os

# ---------- Upload CSV ----------
uploaded = files.upload()
csv_path = next(iter(uploaded.keys()))

# ---------- Load column ----------
def load_first_column(csv_path, col_name="x"):
    df = pd.read_csv(csv_path)
    print("Columns:", df.columns)
    if col_name in df.columns:
        data = df[col_name].astype(float).values
    else:
        data = df.iloc[:,0].astype(float).values
    return data, df

data, df = load_first_column(csv_path)

# ---------- Dummy generalized log-likelihood ----------
# (This is REQUIRED — CRLB cannot exist otherwise)
def generalized_loglike(theta, x):
    return -0.5 * (x - theta)**2   # generic quadratic form

# ---------- Generalized CRLB ----------
def generalized_crlb(theta, log_likelihood, data, eps=1e-6):
    data = np.asarray(data, dtype=float)
    N = data.size

    def score(theta, x):
        return (log_likelihood(theta + eps, x) -
                log_likelihood(theta - eps, x)) / (2 * eps)

    scores = np.array([score(theta, x) for x in data])
    fisher = N * np.mean(scores**2)
    return 1.0 / fisher

# ---------- Compute ----------
theta_test = np.mean(data)
crlb = generalized_crlb(theta_test, generalized_loglike, data)

print("\nCRLB =", crlb)

from google.colab import files

uploaded = files.upload()     # file chooser will open
csv_path = next(iter(uploaded.keys()))

print("Uploaded file:", csv_path)
import pandas as pd
import numpy as np

def load_first_column(csv_path, col_name="x"):
    df = pd.read_csv(csv_path)
    print("Columns in CSV:", list(df.columns))

    if col_name in df.columns:
        data = df[col_name].astype(float).values
        print(f"Using column: '{col_name}'")
    else:
        data = df.iloc[:, 0].astype(float).values
        print(f"Column '{col_name}' not found. Using first column: '{df.columns[0]}'")

    return data, df

data, df = load_first_column(csv_path, col_name="x")

print("\nFirst 10 samples:")
print(data[:10])
print("N =", data.size)

# ---------- Generalized model library ----------

def quadratic_location(theta, x):
    """
    Generic location model (not tied to Gaussian normalization)
    log f(x;θ) ∝ - (x - θ)^2
    """
    return -(x - theta)**2


def absolute_location(theta, x):
    """
    Laplacian-type location model
    """
    return -np.abs(x - theta)


def power_model(theta, x):
    """
    Scale / power-law type model
    """
    return - (x / theta)**2


def exponential_type(theta, x):
    """
    Generic exponential family-like model
    """
    return -x / theta - np.log(theta)
MODEL_REGISTRY = {
    "quadratic": quadratic_location,
    "absolute": absolute_location,
    "power": power_model,
    "exponential": exponential_type
}
def generalized_crlb(theta, log_likelihood, data, eps=1e-6):
    data = np.asarray(data, dtype=float)
    N = data.size

    def score(theta, x):
        return (log_likelihood(theta + eps, x)
                - log_likelihood(theta - eps, x)) / (2 * eps)

    scores = np.array([score(theta, x) for x in data])
    fisher = N * np.mean(scores**2)

    if fisher <= 0 or not np.isfinite(fisher):
        raise ValueError("Invalid Fisher information")

    return 1.0 / fisher
theta_test = np.mean(data)

for model_name, loglike in MODEL_REGISTRY.items():
    crlb = generalized_crlb(theta_test, loglike, data)
    print(f"{model_name:12s} → CRLB = {crlb:.6e}")

# only values CRLB
from google.colab import files
import io, os
import numpy as np
import pandas as pd
import sys
from typing import Callable

print("Choose CSV / Excel file to upload (files.upload() dialog will open)...")
uploaded = files.upload()
if not uploaded:
    raise RuntimeError("No file uploaded. Re-run the cell and choose a file via the dialog.")
fname = next(iter(uploaded.keys()))
print(f"Uploaded file: {fname}")

file_bytes = uploaded[fname]
name, ext = os.path.splitext(fname.lower())

# Helper to try reading CSV with several encodings
def try_read_csv(b: bytes):
    encodings = ['utf-8', 'utf-8-sig', 'latin1', 'cp1252']
    for enc in encodings:
        try:
            return pd.read_csv(io.BytesIO(b), encoding=enc)
        except Exception as e:
            last_exc = e
    # If all fail, raise last exception
    raise last_exc

# Read file (auto-detect Excel vs CSV)
if ext in ('.xls', '.xlsx', '.xlsm', '.xlsb'):
    # Excel file: load first sheet (or you can read sheet_name=None to get all)
    try:
        df = pd.read_excel(io.BytesIO(file_bytes), sheet_name=0)
        print("Detected Excel file; loaded first sheet.")
    except Exception as e:
        raise RuntimeError(f"Failed to read Excel file: {e}")
else:
    try:
        df = try_read_csv(file_bytes)
        print("Detected CSV-like file; loaded with automatic encoding fallback.")
    except Exception as e:
        raise RuntimeError(f"Failed to read CSV: tried several encodings. Last error: {e}")

print("Columns in dataframe:", list(df.columns))
COLUMN_NAME = "x"
if COLUMN_NAME in df.columns:
    col = COLUMN_NAME
    print(f"Using column: '{COLUMN_NAME}'")
else:
    numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
    if len(numeric_cols) > 0:
        col = numeric_cols[0]
        print(f"Column '{COLUMN_NAME}' not found; using first numeric column: '{col}'")
    else:
        col = df.columns[0]
        print(f"No numeric columns found; using first column '{col}' and attempting to coerce to numeric")

# Convert to numeric and drop NaNs
data_series = pd.to_numeric(df[col], errors='coerce')
n_before = data_series.size
data_series = data_series.dropna()
n_after = data_series.size
if n_after == 0:
    raise RuntimeError(f"Column '{col}' contains no numeric data after coercion. Check the file.")
print(f"Kept {n_after}/{n_before} numeric samples from column '{col}'")

data = data_series.values.astype(float)
print("First 10 samples:", data[:10])
print("N =", data.size)

#  Model log-likelihoods & vectorized score functions
SQRT2PI = np.sqrt(2 * np.pi)

def gaussian_loglike(theta: float, x: np.ndarray, sigma: float = 1.0) -> np.ndarray:
    z = (x - theta) / sigma
    return -0.5 * z**2 - np.log(sigma * SQRT2PI)

def gaussian_score(theta: float, x: np.ndarray, sigma: float = 1.0) -> np.ndarray:
    return (x - theta) / (sigma ** 2)

def laplace_loglike(theta: float, x: np.ndarray, b: float = 1.0) -> np.ndarray:
    return - np.abs(x - theta) / b - np.log(2 * b)

def laplace_score(theta: float, x: np.ndarray, b: float = 1.0) -> np.ndarray:
    s = np.sign(x - theta)
    return s / b

def exp_power_loglike(theta: float, x: np.ndarray, sigma: float = 1.0, beta: float = 2.0) -> np.ndarray:
    z = np.abs(x - theta) / sigma
    return - (z ** beta) - np.log(sigma)

def exp_power_score(theta: float, x: np.ndarray, sigma: float = 1.0, beta: float = 2.0) -> np.ndarray:
    diff = x - theta
    absdiff = np.abs(diff)
    with np.errstate(divide='ignore', invalid='ignore'):
        term = beta * np.sign(diff) * (absdiff / sigma) ** (beta - 1) / sigma
    term = np.where(absdiff == 0.0, 0.0, term)
    return term

MODEL_REGISTRY = {
    "gaussian": (gaussian_loglike, gaussian_score),
    "laplace":  (laplace_loglike, laplace_score),
    "exp_power": (exp_power_loglike, exp_power_score)
}

def generalized_crlb(theta: float,
                     score_func: Callable[[float, np.ndarray], np.ndarray],
                     data: np.ndarray) -> float:
    data = np.asarray(data, dtype=float)
    N = data.size
    if N == 0:
        raise ValueError("Empty data array.")
    scores = score_func(theta, data)
    scores = np.asarray(scores, dtype=float)
    mean_s = scores.mean()
    fisher = N * np.mean((scores - mean_s) ** 2)
    if not np.isfinite(fisher) or fisher <= 0:
        raise ValueError(f"Invalid Fisher information estimate: {fisher}")
    return 1.0 / fisher

#  Run models and print CRLBs
theta_test = np.mean(data)
sigma_est = np.std(data, ddof=0)
b_est = sigma_est / np.sqrt(2.0)

print(f"\nUsing theta_test = {theta_test:.6g}, sigma_est ≈ {sigma_est:.6g}, laplace b_est ≈ {b_est:.6g}\n")

for name, (llf, scf) in MODEL_REGISTRY.items():
    try:
        if name == "gaussian":
            crlb_val = generalized_crlb(theta_test, lambda th, x: scf(th, x, sigma=sigma_est), data)
        elif name == "laplace":
            crlb_val = generalized_crlb(theta_test, lambda th, x: scf(th, x, b=b_est), data)
        elif name == "exp_power":
            beta = 1.6
            crlb_val = generalized_crlb(theta_test, lambda th, x: scf(th, x, sigma=sigma_est, beta=beta), data)
        else:
            crlb_val = generalized_crlb(theta_test, scf, data)
        print(f"{name:10s} → CRLB (var bound) = {crlb_val:.6e}")
    except Exception as e:
        print(f"{name:10s} → error estimating CRLB: {e}")

print("\nQuick sample summary:")
print(df.describe(include='all').T)

# Full Colab cell: force upload of a new Excel/CSV, compute CRLBs, plot, save & zip results.
# Paste into Google Colab and run.
from google.colab import files
import io, os, sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import zipfile
from typing import Callable

plt.rcParams.update({"figure.autolayout": True})

def load_new_data_via_upload(prefer_column: str = "x", sheet_name=0):
    """Force upload and return 1D numpy array of numeric data from chosen column."""
    print("Please upload your CSV or Excel file (upload dialog will open)...")
    uploaded = files.upload()
    if not uploaded:
        raise RuntimeError("No file uploaded.")
    fname = next(iter(uploaded.keys()))
    print(f"Uploaded file: {fname}")
    b = uploaded[fname]
    name, ext = os.path.splitext(fname.lower())

    # Quick magic check for xlsx (zip signature 'PK')
    is_xlsx_magic = isinstance(b, (bytes, bytearray)) and b[:2] == b'PK'

    # Try Excel when extension indicates it or magic bytes suggest it
    df = None
    if ext in ('.xls', '.xlsx', '.xlsm', '.xlsb') or is_xlsx_magic:
        try:
            df = pd.read_excel(io.BytesIO(b), sheet_name=sheet_name)
            print("Read file as Excel (first sheet loaded).")
        except Exception as e:
            print("pd.read_excel failed:", e)
            print("Falling back to CSV read attempts...")

    if df is None:
        # Try CSV with common encodings
        encodings = ['utf-8', 'utf-8-sig', 'latin1', 'cp1252']
        last_exc = None
        for enc in encodings:
            try:
                df = pd.read_csv(io.BytesIO(b), encoding=enc)
                print(f"Read file as CSV using encoding='{enc}'.")
                break
            except Exception as e:
                last_exc = e
        if df is None:
            try:
                df = pd.read_csv(io.BytesIO(b), engine='python')
                print("Read file as CSV using engine='python' fallback.")
            except Exception as e:
                raise RuntimeError(f"Failed to read uploaded file as Excel or CSV. Last error: {last_exc or e}")

    print("Columns detected:", list(df.columns))

    # Choose column: prefer 'prefer_column' if present, else first numeric, else first column coerced
    if prefer_column in df.columns:
        col = prefer_column
        print(f"Using preferred column '{prefer_column}'.")
    else:
        numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
        if numeric_cols:
            col = numeric_cols[0]
            print(f"No column '{prefer_column}' found; using first numeric column '{col}'.")
        else:
            col = df.columns[0]
            print(f"No numeric columns found; using first column '{col}' and coercing to numeric.")

    series = pd.to_numeric(df[col], errors='coerce')
    n_before = series.size
    series = series.dropna()
    n_after = series.size
    if n_after == 0:
        raise RuntimeError(f"After coercion, column '{col}' has no numeric data.")
    print(f"Loaded {n_after}/{n_before} numeric samples from column '{col}'.")

    return series.values.astype(float), df, col, fname

# ---------- Force upload now ----------
# If you want to change which column to prefer, set prefer_col variable before calling.
prefer_col = "x"   # change to the column name you want if not 'x'
data, df, used_col, uploaded_name = load_new_data_via_upload(prefer_column=prefer_col)

# ---------- CRLB functions ----------
SQRT2PI = np.sqrt(2 * np.pi)

def gaussian_score(theta: float, x: np.ndarray, sigma: float = 1.0) -> np.ndarray:
    return (x - theta) / (sigma ** 2)

def laplace_score(theta: float, x: np.ndarray, b: float = 1.0) -> np.ndarray:
    s = np.sign(x - theta)
    return s / b

def exp_power_score(theta: float, x: np.ndarray, sigma: float = 1.0, beta: float = 2.0) -> np.ndarray:
    diff = x - theta
    absdiff = np.abs(diff)
    with np.errstate(divide='ignore', invalid='ignore'):
        term = beta * np.sign(diff) * (absdiff / sigma) ** (beta - 1) / sigma
    term = np.where(absdiff == 0.0, 0.0, term)
    return term

def generalized_crlb(theta: float, score_func: Callable[[float, np.ndarray], np.ndarray], data: np.ndarray) -> float:
    data = np.asarray(data, dtype=float)
    N = data.size
    if N == 0:
        return np.nan
    scores = score_func(theta, data)
    scores = np.asarray(scores, dtype=float)
    mean_s = scores.mean()
    fisher = N * np.mean((scores - mean_s) ** 2)
    if not np.isfinite(fisher) or fisher <= 0:
        return np.nan
    return 1.0 / fisher

# ---------- Estimates and output folder ----------
theta_hat = np.mean(data)
sigma_hat = np.std(data, ddof=0)
b_hat = sigma_hat / np.sqrt(2.0)
print(f"Using uploaded data '{uploaded_name}', column '{used_col}'.")
print(f"N={data.size}, theta_hat={theta_hat:.6g}, sigma_hat={sigma_hat:.6g}, b_hat≈{b_hat:.6g}")

out_dir = "crlb_plots_new_upload"
os.makedirs(out_dir, exist_ok=True)

# ---------- Plot 1: CRLB vs sample size (subsampling) ----------
min_N = min(50, max(10, data.size // 10))
Ns = np.unique(np.round(np.linspace(min_N, data.size, 18)).astype(int))
trials = 60

crlb_means = []
crlb_stds = []
for n in Ns:
    vals = []
    for t in range(trials):
        sub = data if n == data.size else np.random.choice(data, size=n, replace=False)
        val = generalized_crlb(np.mean(sub), lambda th, x: gaussian_score(th, x, sigma=sigma_hat), sub)
        vals.append(val)
    vals = np.array(vals, dtype=float)
    crlb_means.append(np.nanmean(vals))
    crlb_stds.append(np.nanstd(vals))

crlb_means = np.array(crlb_means)
crlb_stds = np.array(crlb_stds)

plt.figure(figsize=(9,5))
plt.errorbar(Ns, crlb_means, yerr=crlb_stds, marker='o', linestyle='-')
plt.xlabel('Subsample size N')
plt.ylabel('Estimated CRLB (variance bound)')
plt.title('Gaussian CRLB estimate vs sample size (subsampling)')
plt.grid(True)
p1 = os.path.join(out_dir, "crlb_vs_N_new_upload.png")
plt.savefig(p1, dpi=200)
plt.show()
print("Saved:", p1)

# save table
crlb_vs_n_df = pd.DataFrame({"N": Ns, "crlb_mean": crlb_means, "crlb_std": crlb_stds})
csv_crlb_vs_n = os.path.join(out_dir, "crlb_vs_N_table_new_upload.csv")
crlb_vs_n_df.to_csv(csv_crlb_vs_n, index=False)
print("Saved:", csv_crlb_vs_n)

# ---------- Plot 2: CRLB vs sigma ----------
sigmas = np.linspace(max(1e-8, sigma_hat * 0.2), sigma_hat * 2.5, 30)
crlb_emp = []
crlb_theory = []
for s in sigmas:
    crlb_emp.append(generalized_crlb(theta_hat, lambda th, x: gaussian_score(th, x, sigma=s), data))
    crlb_theory.append((s ** 2) / data.size)

crlb_emp = np.array(crlb_emp)
crlb_theory = np.array(crlb_theory)

plt.figure(figsize=(9,5))
plt.plot(sigmas, crlb_emp, marker='o', linestyle='-')
plt.plot(sigmas, crlb_theory, marker='s', linestyle='--')
plt.xlabel('Assumed sigma (scale)')
plt.ylabel('CRLB (variance bound)')
plt.title('CRLB vs assumed sigma — empirical vs theoretical (Gaussian)')
plt.legend(['Empirical (score-based)', 'Theoretical s^2/N'])
plt.grid(True)
p2 = os.path.join(out_dir, "crlb_vs_sigma_new_upload.png")
plt.savefig(p2, dpi=200)
plt.show()
print("Saved:", p2)

# ---------- Plot 3: model comparison ----------
models = [
    ('Gaussian', lambda th, x: gaussian_score(th, x, sigma=sigma_hat)),
    ('Laplace', lambda th, x: laplace_score(th, x, b=b_hat)),
    ('ExpPower (β=1.6)', lambda th, x: exp_power_score(th, x, sigma=sigma_hat, beta=1.6)),
    ('ExpPower (β=2.0)', lambda th, x: exp_power_score(th, x, sigma=sigma_hat, beta=2.0)),
]
crlbs = []
for name, scoref in models:
    val = generalized_crlb(theta_hat, scoref, data)
    crlbs.append(val)
plt.figure(figsize=(9,4.5))
xpos = np.arange(len(models))
plt.bar(xpos, crlbs, alpha=0.9)
plt.xticks(xpos, [m[0] for m in models], rotation=20)
plt.ylabel('Estimated CRLB (variance bound)')
plt.title('CRLB estimates for different model score functions')
plt.grid(axis='y')
p3 = os.path.join(out_dir, "crlb_model_comparison_new_upload.png")
plt.savefig(p3, dpi=200)
plt.show()
print("Saved:", p3)

# ---------- Plot 4: histogram with fits ----------
plt.figure(figsize=(9,5))
plt.hist(data, bins='auto', density=True, alpha=0.6)
xs = np.linspace(np.min(data), np.max(data), 480)
gauss_pdf = (1.0 / (sigma_hat * np.sqrt(2 * np.pi))) * np.exp(-0.5 * ((xs - theta_hat) / sigma_hat) ** 2)
laplace_pdf = (1.0 / (2 * b_hat)) * np.exp(-np.abs(xs - theta_hat) / b_hat)
plt.plot(xs, gauss_pdf, linestyle='-', linewidth=1.6)
plt.plot(xs, laplace_pdf, linestyle='--', linewidth=1.6)
plt.xlabel('x')
plt.ylabel('Density')
plt.title('Data histogram with fitted Gaussian and Laplace PDFs (theta=mean)')
plt.legend(['Gaussian fit', 'Laplace fit', 'Histogram'])
plt.grid(True)
p4 = os.path.join(out_dir, "hist_with_fits_new_upload.png")
plt.savefig(p4, dpi=200)
plt.show()
print("Saved:", p4)

# ---------- Summary, zip & download ----------
summary = {
    "uploaded_file": uploaded_name,
    "used_column": used_col,
    "N_samples": int(data.size),
    "theta_hat": float(theta_hat),
    "sigma_hat": float(sigma_hat),
    "b_hat": float(b_hat),
    "crlb_gaussian": float(generalized_crlb(theta_hat, lambda th,x: gaussian_score(th, x, sigma=sigma_hat), data)),
    "crlb_laplace": float(generalized_crlb(theta_hat, lambda th,x: laplace_score(th, x, b=b_hat), data)),
    "crlb_exppower_b16": float(generalized_crlb(theta_hat, lambda th,x: exp_power_score(th, x, sigma=sigma_hat, beta=1.6), data)),
    "crlb_exppower_b20": float(generalized_crlb(theta_hat, lambda th,x: exp_power_score(th, x, sigma=sigma_hat, beta=2.0), data))
}
summary_df = pd.DataFrame([summary])
summary_csv = os.path.join(out_dir, "crlb_summary_new_upload.csv")
summary_df.to_csv(summary_csv, index=False)
print("Saved:", summary_csv)

zip_name = "crlb_results_new_upload.zip"
with zipfile.ZipFile(zip_name, 'w', zipfile.ZIP_DEFLATED) as zf:
    for fn in os.listdir(out_dir):
        zf.write(os.path.join(out_dir, fn), arcname=fn)
    zf.write(summary_csv, arcname=os.path.basename(summary_csv))
    zf.write(csv_crlb_vs_n, arcname=os.path.basename(csv_crlb_vs_n))

print("Created zip:", zip_name)
try:
    files.download(zip_name)
    print("Download started for", zip_name)
except Exception:
    print("If automatic download didn't start, fetch the zip from the Files pane or run:")
    print(f"from google.colab import files; files.download('{zip_name}')")

print("All done — new data uploaded, processed, plotted, and saved in folder:", out_dir)